# Chart repositories used from within this state file
#
# Use `helm-s3` and `helm-git` and whatever Helm Downloader plugins
# to use repositories other than the official repository or one backend by chartmuseum.
repositories:
- name: stable
  url: https://charts.helm.sh/stable

- name: argo
  url: https://argoproj.github.io/argo-helm

releases:
  - name: argo                         
    namespace: argocd                     
    chart: argo/argo-cd
    version: ~3.12.1                     
