prometheus-operator:
  defaultRules:
    create: false
    rules: 
      alertmanager: false
      etcd: false
      general: false
      k8s: false
      kubeApiserver: false
      kubeApiserverAvailability: false
      kubeApiserverError: false
      kubeApiserverSlos: false
      kubelet: false
      kubePrometheusGeneral: false
      kubePrometheusNodeAlerting: false
      kubePrometheusNodeRecording: false
      kubernetesAbsent: false
      kubernetesApps: false
      kubernetesResources: false
      kubernetesStorage: false
      kubernetesSystem: false
      kubeScheduler: false
      kubeStateMetrics: false
      network: false
      node: false
      prometheus: false
      prometheusOperator: false
      time: false

alertmanager:
  enabled: false