---
apiVersion: v1
data:
  EXAMPLE_O: ZXhhbXBwbGU=
  EXAMPLE_FIX: ZXhhbXBwbGU=
kind: Secret
metadata:
  annotations:
    someAnnotation: myExampleAnnotation
  name: overlay-new-secret-dev
type: Opaque
