apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: argocd/prometheus
    repoURL: https://github.com/kuzm1ch/bootstrap-aws-eksctl
    targetRevision: master
