apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-guestbook-overlay
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kustomize-guestbook
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: argocd/kustomize/overlays/dev/example-app
    repoURL: https://github.com/kuzm1ch/bootstrap-aws-eksctl
    targetRevision: {{ .Values.spec.source.targetRevision }}
